Vagrant.configure('2') do |config|
        config.vm.box = 'ubuntu_x86_64'
	config.vm.network "forwarded_port", guest: 8080, host: 8086

        config.vbguest.auto_update = true

        config.ssh.forward_agent = true
        config.vm.provision "shell" do |s|
                s.path  = "provision.sh"
        end
end

