Vagrant.configure('2') do |config|
        config.vm.box = 'ubuntu_x86_64'
	config.vm.box_url = 'https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.10/ubuntu-14.10-amd64.box'
	config.vm.network "forwarded_port", guest: 8080, host: 8086

	config.vm.synced_folder ".", "/vagrant", disabled: true

        config.ssh.forward_agent = true
        config.vm.provision "shell" do |s|
                s.path  = "provision.sh"
        end
end

