Vagrant.configure('2') do |config|
        config.vm.box = 'archlinux_x86_64'
        config.vm.box_url = 'http://cloud.terry.im/vagrant/archlinux-x86_64.box'
        config.vm.synced_folder '../.shared/code', '/home/vagrant/code'
        config.vm.synced_folder '../.shared/files', '/home/vagrant/files'

        config.vbguest.auto_update = false

        config.ssh.forward_agent = true
        config.vm.provision "shell" do |s|
                s.path  = "provision.sh"
        end
end

