Vagrant.configure('2') do |config|
        config.ssh.forward_agent = true
	HEADLESS_SCRIPT_DIR = File.dirname(__FILE__) << '/'

	config.vm.box = 'archlinux_x86_64'
	config.vm.box_url = 'http://cloud.terry.im/vagrant/archlinux-x86_64.box'
        config.vm.provision "shell" do |s|
                s.path  = HEADLESS_SCRIPT_DIR + 'deps/archlinux_deps.sh'
        end
        config.vm.provision "shell" do |s|
                s.path  = HEADLESS_SCRIPT_DIR + 'provision.sh'
        end
end

