Vagrant.configure("2") do |config|
	config.vm.box = "precise64"
	config.vm.hostname = "editor"
	config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
	config.vm.synced_folder "~", "/home/vagrant/sharedhome"
	config.vm.synced_folder "../.shared/code", "/home/vagrant/code"
	config.vm.synced_folder "../.shared/files", "/home/vagrant/files"
	# don't forget to have SSH agent forwarding enabled on the host machine
	# you can check if the key is available to the ssh agent by running ssh-add -L
	# ssh-agent; ssh-add; USER=user REMOTEHOST=remotehost PORT=port vagrant up
	config.ssh.forward_agent = true
	config.vm.provision "shell", path: "setup.sh"
	config.vm.provision "shell" do |s|
		s.path 	= "retrieve.sh"
		s.args 	= "-u #{ENV['USER']} -h #{ENV['REMOTEHOST']} -p #{ENV['PORT']}"
	end
	config.vm.provision "shell", :inline -> "rm postinstall.sh"
end

