Vagrant.configure('2') do |config|
	config.vm.box = 'jessie_x86_64'
	config.vm.box_url = 'http://static.gender-api.com/debian-8-jessie-rc2-x64-slim.box'

	config.vbguest.auto_update = false

	config.ssh.forward_agent = true
	config.vm.provision "shell" do |s|
		s.path 	= "provision.sh"
	end
end
