Vagrant.configure("2") do |config|
	config.vm.provider :kvm do |kvm, override|
		kvm.memory_size     = '2G'
		override.vm.box     = 'trusty64'
        	override.vm.box_url = 'https://vagrant-kvm-boxes-si.s3.amazonaws.com/trusty64-kvm-20140418.box'
		kvm.base_mac = "9cc09c2c30c1"
		kvm.core_number = 2
	end
	config.ssh.forward_agent = true
	config.vm.provision "shell" do |s|
		s.path 	= "https://raw.githubusercontent.com/vdloo/dotfiles/master/bootstrap.sh"
		s.args 	= "-u #{ENV['USER']} -s #{ENV['REMOTEHOST']} -p #{ENV['PORT']} -n vagrant"
	end
end
