Vagrant.configure("2") do |config|
	config.vm.box = "CentOS 6.5 x86_64"
	config.vm.hostname = "CentOSLAMPdev64"
	config.vm.network "private_network", type: "dhcp"
	config.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
	config.vm.provision "shell" do |s|
		s.path 	= "https://raw.githubusercontent.com/vdloo/dotfiles/master/bootstrap.sh"
		s.args 	= "-u #{ENV['USER']} -s #{ENV['REMOTEHOST']} -p #{ENV['PORT']} -n vagrant"
	end
end

