begin
	raise RuntimeError, 'Could not use pre-provisioned headless image. Need to run base image playbook as well.'
rescue RuntimeError => e
	puts  e.message
	load '../headless/Vagrantfile'
end

Vagrant.configure('2') do |config|
	case RUBY_PLATFORM
	when /cygwin/, /mingw/
		AUDIO_DRIVER = 'dsound'
	when /darwin/
		AUDIO_DRIVER = 'coreaudio'
	else
		AUDIO_DRIVER = 'alsa'
	end
        config.vm.provider "virtualbox" do |v|
                v.customize ['modifyvm', :id, '--memory', '2048']
                v.customize ['modifyvm', :id, '--cpus', '2']
                v.customize ['modifyvm', :id, '--vram', '256']
                v.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
                v.customize ['modifyvm', :id, '--audio', AUDIO_DRIVER]
                v.customize ['modifyvm', :id, '--audiocontroller', 'ac97']
                v.gui = true
        end
	GUI_SCRIPT_DIR = File.dirname(__FILE__) << '/'
	config.vm.provision "shell" do |s|
		s.path 	= GUI_SCRIPT_DIR + 'provision.sh'
	end
end
