Vagrant.configure("2") do |config|
        config.vm.provider "virtualbox" do |v|
                v.customize ['modifyvm', :id, '--memory', '2048']
                v.customize ['modifyvm', :id, '--cpus', '2']
                v.customize ['modifyvm', :id, '--vram', '128']
                v.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
                v.customize ['modifyvm', :id, '--audio', 'coreaudio']
                v.customize ['modifyvm', :id, '--audiocontroller', 'ac97']
        end
        config.vm.box = "precise64"
        config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
        config.vm.hostname = "XBMC64"
        config.vm.provision :shell, :inline => "apt-get -y update"
        config.vm.provision "shell", path: "setup.sh"
end
