Vagrant.configure("2") do |config|
	config.vm.box = "precise64"
	config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
	config.vm.hostname = "XBMC64"
	config.vm.provision :shell, :inline => "apt-get -y update && apt-get -y install git"
end

