Vagrant.configure("2") do |config|
	config.vm.box = "precise64"
	config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
	config.vm.hostname = "XBMC64"

	config.vm.customize ['modifyvm', :id, '--memory', '2048']
	config.vm.customize ['modifyvm', :id, '--cpus', '2']
	config.vm.customize ['modifyvm', :id, '--vram', '128']
	config.vm.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
	config.vm.customize ['modifyvm', :id, '--audio', 'coreaudio']
	config.vm.customize ['modifyvm', :id, '--audiocontroller', 'ac97']

	config.vm.provision :shell, :inline => "apt-get -y update"
	config.vm.provision "shell", path: "setup.sh"
end

