Vagrant.configure("2") do |config|
        config.vm.box = "trusty64"
        config.vm.box_url = 'https://vagrant-kvm-boxes-si.s3.amazonaws.com/trusty64-kvm-20140418.box'
        config.vm.base_mac = "9cc09c2c30c1"
end
