Vagrant.configure("2") do |config|
        config.vm.box = "trusty64"
        config.vm.box_url = 'https://vagrant-kvm-boxes-si.s3.amazonaws.com/trusty64-kvm-20140418.box'
        config.vm.base_mac = "9cc09c2c30c1"
	config.vm.synced_folder "../.shared/code", "/home/vagrant/code"
	config.vm.synced_folder "../.shared/files", "/home/vagrant/files"
	config.ssh.forward_agent = true
	config.vm.provision "shell" do |s|
		s.path 	= "https://raw.githubusercontent.com/vdloo/dotfiles/master/bootstrap.sh"
		s.args 	= "-u #{ENV['USER']} -s #{ENV['REMOTEHOST']} -p #{ENV['PORT']} -n vagrant"
	end
end
