Vagrant.configure('2') do |config|
	config.vm.box = 'jessie_x86_64'
	config.vm.box_url = 'https://downloads.sourceforge.net/project/vagrantboxjessie/debian80.box'
	config.vm.box_url = 'http://static.gender-api.com/debian-8-jessie-rc2-x64-slim.box'
	config.vm.synced_folder '../.shared/code', '/home/vagrant/code'
	config.vm.synced_folder '../.shared/files', '/home/vagrant/files'
	config.ssh.forward_agent = true
	config.vm.provision :shell do |shell|
		shell.inline = 'wget -P /home/vagrant/ https://raw.githubusercontent.com/vdloo/puppetfiles/master/module/manifests/init.pp;
				mkdir -p /etc/puppet/modules; 
				puppet module install puppetlabs/vcsrepo';
	end
	config.vm.provision 'puppet' do |puppet|
		puppet.manifests_path = ['vm', '/home/vagrant']
		puppet.manifest_file = 'init.pp'
	end
end

