Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
                v.customize ['modifyvm', :id, '--memory', '2048']
                v.customize ['modifyvm', :id, '--cpus', '2']
                v.customize ['modifyvm', :id, '--vram', '128']
                v.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
		# coreaudio for mac. alsa for linux. dsound for windows hosts
                v.customize ['modifyvm', :id, '--audio', 'dsound'] 
                v.customize ['modifyvm', :id, '--audiocontroller', 'ac97']
                v.gui = true
        end

	config.vm.box = "arch_x86_64"
	config.vm.hostname = "arch64"
	config.vm.box_url = 'http://cloud.terry.im/vagrant/archlinux-x86_64.box'
#	config.vm.synced_folder "../.shared/code", "/home/vagrant/code"
#	config.vm.synced_folder "../.shared/files", "/home/vagrant/files"
	config.ssh.forward_agent = true
	config.vm.provision "shell" do |s|
		s.path 	= "https://raw.githubusercontent.com/vdloo/dotfiles/master/bootstrap.sh"
		s.args 	= "-u #{ENV['USER']} -s #{ENV['REMOTEHOST']} -p #{ENV['PORT']} -n vagrant"
	end
	config.vm.provision "shell", path: "post.sh"
end

