Vagrant.configure('2') do |config|
	config.vm.box = 'ubuntu_x86_64'
        config.vm.provider "virtualbox" do |v|
                v.customize ['modifyvm', :id, '--memory', '2048']
                v.customize ['modifyvm', :id, '--cpus', '2']
                v.customize ['modifyvm', :id, '--vram', '256']
                v.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
                # coreaudio for mac. alsa for linux. dsound for windows hosts
                v.customize ['modifyvm', :id, '--audio', 'dsound']
                v.customize ['modifyvm', :id, '--audiocontroller', 'ac97']
                v.gui = true
        end
	config.vm.box_url = 'https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.10/ubuntu-14.10-amd64.box'
	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.ssh.forward_agent = true
	config.vm.provision "shell" do |s|
		s.path 	= "provision.sh"
	end
end
