begin
	raise RuntimeError, 'Could not use pre-provisioned workstation image. Need to run base image playbook as well.'
rescue RuntimeError => e
	puts  e.message
	load '../workstation/Vagrantfile'
end

Vagrant.configure('2') do |config|
        config.vm.provider "virtualbox" do |v|
		# Needs bigger disk
        end
	HTPC_SCRIPT_DIR = File.dirname(__FILE__) << '/'
	config.vm.provision "shell" do |s|
		s.path 	= HTPC_SCRIPT_DIR + 'provision.sh'
	end
end
