Vagrant.configure("2") do |config|
        config.vm.provider "virtualbox" do |v|
                v.customize ['modifyvm', :id, '--memory', '2048']
                v.customize ['modifyvm', :id, '--cpus', '2']
                v.customize ['modifyvm', :id, '--vram', '128']
                v.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
                v.customize ['modifyvm', :id, '--audio', 'dsound'] # coreaudio for mac. dsound for windows hosts
                v.customize ['modifyvm', :id, '--audiocontroller', 'ac97']
		v.gui = true
        end
        config.vm.box = "cloud-images/trusty-tahr"
        config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
        config.vm.hostname = "XBMC64"
        config.vm.provision :shell, :inline => "apt-get -y update && apt-get -y upgrade"
        config.vm.provision "shell", path: "setup.sh"
end
