Vagrant.configure('2') do |config|
	config.vm.box = 'jessie_x86_64'
        config.vm.provider "virtualbox" do |v|
                v.customize ['modifyvm', :id, '--memory', '2048']
                v.customize ['modifyvm', :id, '--cpus', '2']
                v.customize ['modifyvm', :id, '--vram', '256']
                v.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
                # coreaudio for mac. alsa for linux. dsound for windows hosts
                v.customize ['modifyvm', :id, '--audio', 'dsound']
                v.customize ['modifyvm', :id, '--audiocontroller', 'ac97']
                v.gui = true
        end
	config.vm.box_url = 'http://static.gender-api.com/debian-8-jessie-rc2-x64-slim.box'

	config.ssh.forward_agent = true
	config.vm.provision "shell" do |s|
		s.path 	= "provision.sh"
	end
end
